# Composition for development
version: '2'

volumes:
  odoo-data:
  odoo-testlogs:
  psql:

services:
  odoo:
    container_name: odoo
    build: ./odoo/
    ports: ["8069:8069", "8072:8072"]
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo/data
      - ./odoo/config/odoo.conf:/etc/odoo/odoo.conf:delegated
      - ./odoo/custom:/mnt/extra-addons:delegated
      - odoo-testlogs:/var/lib/odoo/logs

  db:
    image: postgres:9.6
#    build: ./postgres/
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

  nginx:
    container_name: nginx
    build: ./nginx/
    #    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
#      - ./certbot/conf:/etc/nginx/ssl
#      - ./certbot/data:/var/www/html
    depends_on:
      - odoo
